- name: Copy multiple files to remote server
  hosts: svdev01
  tasks:
    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: "/home/ansible/sftp/to_raindance/400/tmp/"
      with_items:
        - /home/ansible/ansiblesemaphore/files/raindance/to_raindance/test1.txt
        - /home/ansible/ansiblesemaphore/files/raindance/to_raindance/test2.txt
        - /home/ansible/ansiblesemaphore/files/raindance/to_raindance/test3.txt
