---
- name: Export Personec file from Nextcloud
  hosts: nextcloud_dev
  gather_facts: no
  become: yes
  
  tasks:
    - name: Execute script personec_export.sh
      command: /root/bin/personec_export.sh
      register: script_result
      ignore_errors: yes  # Continue playbook execution even if the script fails

    - name: Handle errors
      debug:
        msg: "The script failed with an exit code of {{ script_result.rc }}"
      when: script_result.rc != 0

    - name: Fail the playbook on error
      fail:
        msg: "Playbook failed because the personec_export.sh script encountered an error"
      when: script_result.rc != 0
