---
- name: Run Bash Script Locally
  hosts: ubuntu
  #connection: local
  gather_facts: no

  tasks:
    - name: Execute the Bash script
      command: /home/ansible/ansiblesemaphore/files/bin/sftp2remote.sh
      register: script_result
      ignore_errors: yes  # Continue playbook execution even if the script fails

    - name: Handle errors
      debug:
        msg: "The script failed with an exit code of {{ script_result.rc }}"
      when: script_result.rc != 0

    # Add more tasks if needed
