---
- name: Personec SFTP to Raindance
  hosts: ubuntu
  gather_facts: no

  tasks:
    - name: Execute script personec_sftp.sh
      command: /home/ansible/ansiblesemaphore/files/bin/personec_sftp.sh
      register: script_result
      ignore_errors: yes  # Continue playbook execution even if the script fails

    - name: Handle errors
      debug:
        msg: "The script failed with an exit code of {{ script_result.rc }}"
      when: script_result.rc != 0

    - name: Fail the playbook on error
      fail:
        msg: "Playbook failed because the personec_sftp.sh script encountered an error"
      when: script_result.rc != 0

